### ISSUE TITLE
bug: localization type or value?

### ISSUE THREAD

**Issue by joshmoore** [German-BioImaging/dtplatform#32]
Data shows localization _being_ a C12354
```
                    wd:P927 [ a obo:NCIT_C12354 ;
                            obo:NCIT_A4 obo:NCIT_C25228 ] ] ;
```
where was graphviz shows rdf:value of C12354:

![Screen Shot 2022-10-05 at 09 01 28](https://user-images.githubusercontent.com/88113/194000031-621f352e-1e2b-4528-a388-a8fb6bbcc20b.png)

**Comment by andrawaag** [comment]
#31

**Comment by joshmoore** [comment]
![Screen Shot 2022-10-05 at 09 21 08](https://user-images.githubusercontent.com/88113/194003258-599225ed-ce16-48c6-9824-9aacc2a58e43.png)

Looks like one more rdf:type arrows needs removing.
