### ISSUE TITLE
bug: double types in graphviz for treatment

### ISSUE THREAD

**Issue by joshmoore** [German-BioImaging/dtplatform#38]
![Screen Shot 2022-10-05 at 12 48 23](https://user-images.githubusercontent.com/88113/194043240-a1c04857-aac6-40ef-8cbf-f34f5fdf240e.png)

**Comment by andrawaag** [comment]
Good catch. There are many things going on here. First there is the error that the stop dates are labels as start data. This is fixed. 

However the double dates do make sense. I considered making single nodes for data types, but the node should reflect distinct dates when applicable. Which clearly showed a modellings issue/error. 

I remodelled the TNBC data to include a list of treatments where all treatments are members of that list. 

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/770306/194068324-c3f51897-c339-4770-b498-7035ac6715db.png">
